<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>IronHive Google AI provider</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="IronHive.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IronHive.Abstractions\IronHive.Abstractions.csproj" />
  </ItemGroup>

</Project>
