<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>IronHive OpenAI provider</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="IronHive.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenAI" />
    <PackageReference Include="Tiktoken.Core" />
    <PackageReference Include="Tiktoken.Encodings.cl100k" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IronHive.Abstractions\IronHive.Abstractions.csproj" />
  </ItemGroup>

</Project>
